baseurl = "//evademl.org"
languageCode = "en-us"
title = "EvadeML"
subtitle = "Adversarial Machine Learning"

[params]
    sidebartitle = "EvadeML"
    sidebartagline = "Machine Learning in the Presence of Adversaries"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[[menu.footer]]
